// <auto-generated />
using EMONAPI.Persistance.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EMONAPI.Migrations
{
    [DbContext(typeof(MeterContext))]
    [Migration("20210625194346_changedDoubleToString")]
    partial class changedDoubleToString
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-rc.2.20475.6");

            modelBuilder.Entity("EMONAPI.Persistance.Entities.FullDatagram", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("currentUsage")
                        .HasColumnType("float");

                    b.Property<double>("gasUsage")
                        .HasColumnType("float");

                    b.Property<double>("returnHigh")
                        .HasColumnType("float");

                    b.Property<double>("returnLow")
                        .HasColumnType("float");

                    b.Property<string>("signature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("timeStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("totalHigh")
                        .HasColumnType("float");

                    b.Property<double>("totalLow")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("datagrams");
                });

            modelBuilder.Entity("EMONAPI.Persistance.Entities.TempratureModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("timeStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tempratures");
                });
#pragma warning restore 612, 618
        }
    }
}
